### ISSUE TITLE
Replace drag and drop placeholders with file inputs

### ISSUE THREAD

**Issue by gocemitevski** [keitaroinc/blog-image-generator#119]
Drag and drop placeholders need to be replaced with file inputs so the user has multiple usage options.

If the user wants to drop a file to the placeholder, that is already possible, however, clicking on the drag and drop placeholder should also offer the option to select a file from a file location.

The look of the placeholders does not need to change, this enhancement is only related to the associated events.

**Comment by aksentijev-nikola** [comment]
This issue has been fix with the following PR:
https://github.com/keitaroinc/blog-image-generator/pull/127
