### ISSUE TITLE
Drag and drop of image files that are not stored locally, does not work in Firefox

### ISSUE THREAD

**Issue by pdonchev1** [keitaroinc/blog-image-generator#55]
In GitLab by @goce.mitevski on May 12, 2023, 09:11

When the user tries to drag and drop an image from any open tab, the image is not loaded until saved as an image to the local file system. This is not the case with Chromium-based browsers.

**Comment by gocemitevski** [comment]
The drag and drop behavior for file uploads has been changed to be triggered on the click event, so this bug is no longer relevant.
